[config]
schemaVersion = "0.0.1"

[package]
namespace = "symmys"
name = "AutoCommandQueuePickup"
versionNumber = "1.0.0"
description = "Automatically pickups up CommandCubes on drop if command queue has been set"
websiteUrl = "https://github.com/sburchil/AutoCommandQueuePickup/tree/dev"
containsNsfwContent = false

[package.dependencies]
bbepis-BepInExPack = "5.4.1905"
RiskofThunder-HookGenPatcher = "1.2.3"

[build]
icon = "./icon.png"
readme = "./README.md"
outdir = "./build"

[[build.copy]]
source = "./ReleaseOutput/ProperSave.dll"
target = "./AutoCommandQueuePickup/"

[[build.copy]]
source = "./CHANGELOG.md"
target = "./CHANGELOG.md"